

default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: map_app_development
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: map_app_test
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>